global using System.Net;
global using CatalogoFilmesSeries.Application.Interfaces;
global using CatalogoFilmesSeries.Application.Services;
global using CatalogoFilmesSeries.Application.Shared;
global using CatalogoFilmesSeries.Domain.Entities;
global using Moq;
global using CatalogoFilmesSeries.Domain.ValueObjects;
global using Microsoft.Extensions.Logging;
global using CatalogoFilmesSeries.Application.Dtos;